---
name: 'post-to-sonarcloud'
description: 'Post results to Sonarcloud'

inputs:
  sonar-token:
    description: 'Sonarcloud project access token.'
    requires: true

runs:
  using: "composite"
  steps:
    - name: Analyze with SonarCloud
      uses: sonarsource/sonarcloud-github-action@master
      with:
        projectBaseDir: .
      env:
        GITHUB_TOKEN: ${{ github.token }}
        SONAR_TOKEN: ${{ inputs.sonar-token }}
...
